swagger: "2.0"
info:
  description: "This is the X-mas MKKP Good-Deed Map Server's REST API"
  version: "0.0.1"
  title: "MKKP Good-Deed Map"
  termsOfService: "https://mkkp.party/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "good-deed.mkkp.party"
basePath: "/v1"
tags:
- name: "deed"
  description: "Basic operations on Deeds"
schemes:
- "https"
- "http"
paths:
  /deed:
    post:
      tags:
      - "Deed"
      summary: "Add a new deed"
      description: "This endpoint creates a new good-deed with its location and deed description"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Deed object"
        required: true
        schema:
          $ref: "#/definitions/Deed"
      responses:
        405:
          description: "Invalid input"
    put:
      tags:
      - "Deed"
      summary: "Update an existing deed"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Deed object to update"
        required: true
        schema:
          $ref: "#/definitions/Deed"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Deed not found"
        405:
          description: "Validation exception"

  /pet/{petId}:
    get:
      tags:
      - "Deed"
      summary: "Find deed by ID"
      description: "Returns a single deed"
      produces:
      - "application/json"
      parameters:
      - name: "deedId"
        in: "path"
        description: "ID of deed to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Deed"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Deed not found"
      security:
      - api_key: []



securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify deeds in your account"
      read:pets: "read your deeds"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:

  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  Deed:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"

  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"